repos:
  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
        exclude: ^poetry/core/_vendor

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
        exclude: |
          (?x)(
              ^poetry/core/utils/_typing.py$
              | ^poetry/core/utils/_compat.py$
              | ^poetry/core/_vendor
          )

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        pass_filenames: false

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        additional_dependencies: [toml]
        exclude: |
          (?x)(
              ^.*/?setup\.py$
              | ^poetry/core/_vendor
              | tests/.*\.pyi$
          )

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)(
              ^tests/.*/fixtures/.*
              | ^poetry/core/_vendor
          )
      - id: end-of-file-fixer
        exclude: |
          (?x)(
              ^tests/.*/fixtures/.*
              | ^poetry/core/_vendor
          )
      - id: debug-statements
        exclude: ^poetry/core/_vendor

      - id: check-json
        exclude: ^poetry/core/_vendor

      - id: pretty-format-json
        exclude: ^poetry/core/_vendor
        args:
          - --no-sort-keys
          - --autofix
