name: Integration

on:
  pull_request: {}

jobs:
  Tests:
    name: Python 3.7
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"

      - name: Install tox
        run: pip install --upgrade tox

      - name: Execute integration tests
        run: tox -e integration
